"""initial schema

Revision ID: 73c601621fe6
Revises:
Create Date: 2026-09-20 01:48:15.779077
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '73c601621fe6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('processing_version', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_document_case_hash')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('document_artifacts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_artifacts_document_id'), 'document_artifacts', ['document_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=180), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_case_id'), 'extracted_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_field_name'), 'extracted_fields', ['field_name'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=False),
    sa.Column('pipeline_version', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('timings_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_runs_case_id'), 'processing_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_processing_runs_document_id'), 'processing_runs', ['document_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('left_document_id', sa.String(length=80), nullable=True),
    sa.Column('right_document_id', sa.String(length=80), nullable=True),
    sa.Column('left_value_json', sa.JSON(), nullable=True),
    sa.Column('right_value_json', sa.JSON(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['left_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['right_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_case_id'), 'reconciliations', ['case_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=True),
    sa.Column('actual_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_case_id'), 'validation_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_validation_results_document_id'), 'validation_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_results_rule_id'), 'validation_results', ['rule_id'], unique=False)
    op.create_table('field_evidence',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('field_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('section', sa.String(length=240), nullable=True),
    sa.Column('artifact_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_evidence_document_id'), 'field_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_field_evidence_field_id'), 'field_evidence', ['field_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('field_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model_value_json', sa.JSON(), nullable=True),
    sa.Column('human_value_json', sa.JSON(), nullable=True),
    sa.Column('reviewer', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_case_id'), 'review_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_items_document_id'), 'review_items', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_document_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_case_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_field_evidence_field_id'), table_name='field_evidence')
    op.drop_index(op.f('ix_field_evidence_document_id'), table_name='field_evidence')
    op.drop_table('field_evidence')
    op.drop_index(op.f('ix_validation_results_rule_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_document_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_case_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_reconciliations_case_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_processing_runs_document_id'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_case_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_extracted_fields_field_name'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_case_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_document_artifacts_document_id'), table_name='document_artifacts')
    op.drop_table('document_artifacts')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
